services:
  - type: web
    name: kkh-nursing-chatbot-api
    runtime: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile.render
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONPATH
        value: /app
      - key: RENDER
        value: "true"
    autoDeploy: true
    branch: main
